package io.github.kmbisset89.worldweaver.domain

/**
 * Form answers collected by the one-shot wizard before they are turned into a [OneShotDraft].
 */
internal data class OneShotAnswers(
    val worldName: String = "",
    val campaignName: String = "",
    val gameSystem: GameSystem = GameSystem.FifthEdition,
    val logline: String = "",
    val genreId: String? = null,
    val toneId: String? = null,
    val hookId: String? = null,
    val hook: String = "",
    val realmName: String = "",
    val regionName: String = "",
    val settlementName: String = "",
    val siteTypeId: String? = null,
    val openingSiteName: String = "",
    val openingSiteDescription: String = "",
    val middleSiteName: String = "",
    val middleSiteDescription: String = "",
    val climaxSiteName: String = "",
    val climaxSiteDescription: String = "",
    val patronName: String = "",
    val patronDescription: String = "",
    val villainName: String = "",
    val villainDescription: String = "",
    val villainKind: PersonKind = PersonKind.Npc,
    val villainTypeId: String? = null,
    val allyName: String = "",
    val allyDescription: String = "",
    val factionName: String = "",
    val factionDescription: String = "",
    val questTitle: String = "",
    val stakes: String = "",
    val objective1: String = "",
    val objective2: String = "",
    val objective3: String = "",
    val objective4: String = "",
    val twist: String = "",
    val sessionName: String = "",
    val openingSceneTitle: String = "",
    val middleSceneTitle: String = "",
    val climaxSceneTitle: String = "",
    val includeEncounter: Boolean = false,
    val encounterName: String = "",
    val encounterDifficulty: EncounterDifficulty = EncounterDifficulty.Medium,
)
